### ISSUE TITLE
Bug in Kirara portrait

### ISSUE THREAD

**Issue by Hidetovtamer** [Medabots/medarot1#182]
I leave you with the video file showing the bug and the .sav so that you can access that easily.

https://user-images.githubusercontent.com/84340957/120121361-61be5800-c179-11eb-8f93-6088c85a8fd0.mp4

[medarot_kabuto_portraits.zip](https://github.com/Medabots/medarot1/files/6566970/medarot_kabuto_portraits.zip)

**Comment by VariantXYZ** [comment]
Issue is that portraits aren't being cleared despite the end code 4F 04, should be an easy fix.

**Comment by VariantXYZ** [comment]
Ah, actual issue isn't due to 4F, it's just because it draws the MainDialog which wipes the drawing area as a result. This is technically incorrect behavior in non-portrait versions too...

**Comment by VariantXYZ** [comment]
Options are to either stop main dialog from loading at that stage (and every other similar situation), or modifying the tileset such that our drawing area isn't in the middle (and therefore prevent it from being wiped).

Both require tedious testing, but the latter doesn't require us to dump a lot more, so it's probably easier.
