### ISSUE TITLE
[Makefile:188: build/tilesets/1156.2bpp] Error 127

### ISSUE THREAD

**Issue by clpacheco90** [Medabots/medarot1#192]
Hi,

When I run `make`  with my baserom (with same md5) , I get the following error:
```js
rgbgfx  -d 2 -o build/tilesets/1156.2bpp text/tilesets/1156.png
make: rgbgfx: No such file or directory
make: *** [Makefile:188: build/tilesets/1156.2bpp] Error 127
make: *** Waiting for unfinished jobs....

```

I run:
```bash
make -j
```

Can you help?

**Comment by VariantXYZ** [comment]
What branch are you on?

**Comment by andwhyisit** [comment]
Are you sure you have rgbds installed in your build environment? What are you using as your build environment? Is it WSL, cygwin, mingw, an actual unix-based command line, or something else?

**Comment by VariantXYZ** [comment]
Also, having the full Make log would be good.

A clean log would help too:

make clean
make -j

**Comment by clpacheco90** [comment]
rgbds was not  installed.
I did not check it. 

After start again I got a ERROR : `glibc2.34 not found`
but was solved when I update it

in my case using arch:
```zh
sudo pacman -Sy lib32-glibc
```
Thank you all for the excellent dedication to the project
