### ISSUE TITLE
"The patch was applied but appears scrambled or malformed" (Flips v1.31)

### ISSUE THREAD

**Issue by MediaMaquina** [Medabots/medarot1#194]
Hello, the patch works but [Floating IPS](https://www.romhacking.net/utilities/1040/) warns there's something wrong with it.
![3](https://user-images.githubusercontent.com/8179611/187070382-005f5362-12e1-4e6f-b99b-60f472840ffc.png)
![2](https://user-images.githubusercontent.com/8179611/187070385-93759a55-e2fe-4d31-af0a-b52709f9ea2a.png)
![1](https://user-images.githubusercontent.com/8179611/187070390-ce4a8d30-11ad-40bb-bfea-85f31dccd7e2.png)

**Comment by VariantXYZ** [comment]
If the output sha1 matches, I'm not sure there's an issue.

This might be a bug with Flips instead of our patch.

**Comment by MediaMaquina** [comment]
No idea just reporting my findings. It's weird that it says that. When it does the games usually don't work.

**Comment by VariantXYZ** [comment]
Do you happen to see this with other versions of the patch?

**Comment by MediaMaquina** [comment]
Hi this seems to be an issue of Flips. No need to do anything. Sorry.
